# Generated by Django 3.1.1 on 2020-09-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tags',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
