# Generated by Django 3.1.1 on 2020-09-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_curso_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='web/static/img/'),
        ),
    ]
