# Generated by Django 3.1.1 on 2020-10-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pelicula'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
