# Generated by Django 3.0.5 on 2020-10-10 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='imagen',
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen_principal',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='adjuntos/'),
        ),
        migrations.CreateModel(
            name='ImagenCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Curso')),
            ],
        ),
    ]
