# Generated by Django 3.1.2 on 2020-10-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20201010_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagencurso',
            name='nombre',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
