# Generated by Django 3.1.2 on 2020-10-23 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201016_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
