# Generated by Django 3.1.2 on 2020-10-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20201016_2227'),
        ('web', '0004_curso_image_path'),
    ]

    operations = [
    ]
